modLoader="javafml"
loaderVersion="[38,)"
license="BSD (3 clause)"
issueTrackerURL="https://github.com/Wintersky20"

[[mods]]
    modId="workbench"
    version="${file.jarVersion}"
    displayName="Workbench"
    logoFile="logo.png"
    description='''
'''
    credits="Thanks to Sewing Kit mod an Chipped for exemples"
    authors="wintersky"
    displayURL="https://github.com/Wintersky20"

[[dependencies.workbench]]
    modId="forge"
    mandatory=true
    versionRange="[38.0.10,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.workbench]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.workbench]]
    modId="jei"
    mandatory=false
    versionRange="[9.5,)"
    ordering="NONE"
    side="BOTH"
