@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.wintersky.workbench;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;