@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.wintersky.workbench.integration;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;